services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ideas_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql